name: CI/CD

on:
  push:
    branches:
      - master
      - dev
  workflow_dispatch:

concurrency: ${{ github.ref }}

env:
  ENV_KEY: env-vars
  ENV_FILE: env.yaml
  PROJECT_ID: luux-media
  GCP_SA: etl-158@luux-media.iam.gserviceaccount.com

jobs:
  set-env:
    runs-on: ubuntu-latest
    outputs:
      fn-name: ${{ steps.set-fn-name.outputs.fn-name }}
      public-url: ${{ steps.set-fn-name.outputs.fn-name }}

    steps:
      - name: Set env vars (dev)
        if: github.ref_name == 'dev'
        run: |
          echo "FUNCTION_NAME=luux-media-emails-dev" >> $GITHUB_ENV
          echo "PUBLIC_URL=https://us-central1-luux-media.cloudfunctions.net/luux-media-emails-dev" >> $GITHUB_ENV

      - name: Set env vars (prod)
        if: github.ref_name == 'master'
        run: |
          echo "FUNCTION_NAME=luux-media-emails" >> $GITHUB_ENV
          echo "PUBLIC_URL=https://us-central1-luux-media.cloudfunctions.net/luux-media-emails" >> $GITHUB_ENV

      - id: set-fn-name
        name: Set Function Name
        run: echo "::set-output name=fn-name::${{ env.FUNCTION_NAME}}"

      - name: Create ${{ env.ENV_KEY }}
        run: |
          echo "SENDER_PWD: ${{ secrets.SENDER_PWD }}" >> ${{ env.ENV_FILE }}
          echo "GCP_SA: ${{ env.GCP_SA }}" >> ${{ env.ENV_FILE }}
          echo "PUBLIC_URL: ${{ env.PUBLIC_URL }}" >> ${{ env.ENV_FILE }}

      - name: Upload ${{ env.ENV_FILE }}
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.ENV_KEY }}
          path: ${{ env.ENV_FILE }}
          
  deploy:
    runs-on: ubuntu-latest
    needs: set-env
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download ${{ env.ENV_FILE }}
        uses: actions/download-artifact@v2
        with:
          name: ${{ env.ENV_KEY }}

      - name: Auth
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}"

      - name: Deploy to Cloud Functions
        run: >-
          gcloud functions deploy ${{ needs.set-env.outputs.fn-name }}
          --entry-point=main
          --region=us-central1
          --timeout=530
          --memory=1024MB
          --runtime=python39
          --trigger-http
          --no-user-output-enabled
          --service-account=${{ env.GCP_SA }}
          --env-vars-file=${{ env.ENV_FILE }}

  clean-up:
    runs-on: ubuntu-latest
    needs: deploy
    if: ${{ always() }}
    steps:
      - run: echo "" > ${{ env.ENV_FILE }}

      - uses: actions/upload-artifact@v2
        with:
          name: ${{ env.ENV_KEY }}
          path: ${{ env.ENV_FILE }}
