name: CI/CD

on:
  push:
    branches: [master]
  workflow_dispatch:

concurrency: ${{ github.ref }}

env:
  ENV_KEY: env-vars
  ENV_FILE: env.yaml
  FUNCTION_NAME: luux-media-emails
  PROJECT_ID: luux-media
  GCP_SA: etl-158@luux-media.iam.gserviceaccount.com
  PUBLIC_URL: https://us-central1-luux-media.cloudfunctions.net/luux-media-emails

jobs:
  set-env:
    runs-on: ubuntu-latest
    steps:
      - name: Create ${{ env.ENV_KEY }}
        run: |
          echo "SENDER_PWD: ${{ secrets.SENDER_PWD }}" >> ${{ env.ENV_FILE }}
          echo "GCP_SA: ${{ env.GCP_SA }}" >> ${{ env.ENV_FILE }}
          echo "PUBLIC_URL: ${{ env.PUBLIC_URL }}" >> ${{ env.ENV_FILE }}

      - name: Upload ${{ env.ENV_FILE }}
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.ENV_KEY }}
          path: ${{ env.ENV_FILE }}
          
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download ${{ env.ENV_FILE }}
        uses: actions/download-artifact@v2
        with:
          name: ${{ env.ENV_KEY }}

      - name: Auth
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}"

      - name: Deploy
        uses: google-github-actions/deploy-cloud-functions@v0
        with:
          name: ${{ env.FUNCTION_NAME }}
          entry_point: main
          runtime: python39
          memory_mb: 512MB,
          timeout: 530,
          service_account_email: ${{ env.GCP_SA }}
          env_vars_file: ${{ env.ENV_FILE }}

  clean-up:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - run: echo "" > ${{ env.ENV_FILE }}

      - uses: actions/upload-artifact@v2
        with:
          name: ${{ env.ENV_KEY }}
          path: ${{ env.ENV_FILE }}
